### ISSUE TITLE
ImportError: cannot import name 'By' from 'selenium_firefox.firefox' 

### ISSUE THREAD

**Issue by VitharMe** [linouk23/youtube_uploader_selenium#13]
```
$ python3 upload.py --video video.mp4
Traceback (most recent call last):
  File "upload.py", line 2, in <module>
    from youtube_uploader_selenium import YouTubeUploader
  File "/home/test/projetcs/youtube_uploader_selenium/youtube_uploader_selenium/__init__.py", line 5, in <module>
    from selenium_firefox.firefox import Firefox, By, Keys
ImportError: cannot import name 'By' from 'selenium_firefox.firefox' (/home/test/.local/lib/python3.7/site-packages/selenium_firefox/firefox.py)
```

**Comment by ankitsiliconithub** [comment]
how you solved it ?
