### ISSUE TITLE
Crashing in the youtube "Checks" section of the upload

### ISSUE THREAD

**Issue by DrixGod** [linouk23/youtube_uploader_selenium#46]
DEBUG:youtube_uploader_selenium:Attached video test.mp4
DEBUG:youtube_uploader_selenium:The video title was set to "Best Of James Harden | 2019-20 NBA Season"
DEBUG:youtube_uploader_selenium:The video description was set to "Check out the best of James Harden's 2019-20 season so far!"
DEBUG:youtube_uploader_selenium:Selected "NOT_MADE_FOR_KIDS"
DEBUG:youtube_uploader_selenium:Clicked next-button
DEBUG:youtube_uploader_selenium:Clicked another next-button
'NoneType' object has no attribute 'click'
Traceback (most recent call last):
  File "E:/dev/uploady/eradinus.py", line 11, in <module>
    was_video_uploaded, video_id = uploader.upload()
  File "E:\dev\Anaconda\lib\site-packages\youtube_uploader_selenium\__init__.py", line 47, in upload
    return self.__upload()
  File "E:\dev\Anaconda\lib\site-packages\youtube_uploader_selenium\__init__.py", line 110, in __upload
    self.browser.find(By.ID, Constant.RADIO_LABEL, public_main_button).click()
AttributeError: 'NoneType' object has no attribute 'click'

Process finished with exit code 1

The next button in the checks column is blue and can be clicked but the program waits for 10 seconds and crashes here.

**Comment by DrixGod** [comment]
Manually clicking next in that steps still leads to a crash

Traceback (most recent call last):
  File "E:/dev/uploady/eradinus.py", line 12, in <module>
    was_video_uploaded, video_id = uploader.upload()
  File "E:\dev\Anaconda\lib\site-packages\youtube_uploader_selenium\__init__.py", line 47, in upload
    return self.__upload()
  File "E:\dev\Anaconda\lib\site-packages\youtube_uploader_selenium\__init__.py", line 118, in __upload
    in_process = status_container.text.find(Constant.UPLOADED) != -1
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by gartha1** [comment]
easiest thing is set the whole youtube channel to "made for kids" or "not made for kids", as you require,  And then the option won't come up when you want to upload a video.

And re the code, it has stuff that sets that on a per video basis. You can then comment out that part of the code that sets the "made for kids / not made for kids" option. It's around that point where I commented parts out and customized it re what it clicks. e.g. I didn't want it clicking next buttons I want it to click what I wanted it to click eg visibility private.
