### ISSUE TITLE
__init__() got an unexpected keyword argument 'firefox_options'

### ISSUE THREAD

**Issue by JoyQu** [linouk23/youtube_uploader_selenium#56]
Traceback (most recent call last):
  File "F:\test\222\youtube_uploader_selenium-master\uup.py", line 7, in <module>
    uploader = YouTubeUploader(video_path, metadata_path, thumbnail_path)
  File "F:\test\222\youtube_uploader_selenium-master\youtube_uploader_selenium\__init__.py", line 33, in __init__
    self.browser = Firefox(current_working_dir, current_working_dir)
  File "F:\test\222\youtube_uploader_selenium-master\venv\lib\site-packages\selenium_firefox\firefox.py", line 86, in __init__
    self.driver = webdriver.Firefox(firefox_profile=profile, firefox_options=options)
TypeError: __init__() got an unexpected keyword argument 'firefox_options'

How to solve this problem ？

**Comment by JoyQu** [comment]
its works now!

**Comment by andersonfelipev** [comment]
How did you solve this problem? I'm in the sema error

**Comment by linzhoulxyz** [comment]
> How did you solve this problem? I'm in the same error

check your selenium version.  

pip install selenium==3.141.0 work for me

**Comment by JoyQu** [comment]
> 你是如何解决这个问题的？我有同样的错误

self.driver = webdriver.Firefox(firefox_profile=profile, firefox_options=options)
just modify   **firefox_options** --> options
