### ISSUE TITLE
selenium_firefox

### ISSUE THREAD

**Issue by JaxonPlays** [linouk23/youtube_uploader_selenium#64]
`F:\YouTube\Other archive stuff\youtube_uploader_selenium-master\youtube_uploader_selenium-master>python upload.py
Traceback (most recent call last):
  File "F:\YouTube\Other archive stuff\youtube_uploader_selenium-master\youtube_uploader_selenium-master\upload.py", line 2, in <module>
    from youtube_uploader_selenium import YouTubeUploader
  File "F:\YouTube\Other archive stuff\youtube_uploader_selenium-master\youtube_uploader_selenium-master\youtube_uploader_selenium\__init__.py", line 5, in <module>
    from selenium_firefox.firefox import Firefox, By, Keys
ModuleNotFoundError: No module named 'selenium_firefox'`

**Comment by craway** [comment]
just install the module
