### ISSUE TITLE
error of WebDriverException  (that's after having resolved TypeError: WebDriver.__init__()) 

### ISSUE THREAD

**Issue by gartha1** [linouk23/youtube_uploader_selenium#70]
i'm getting this error

C:\pythontest\youtube_uploader_selenium>dir
 Volume in drive C is Local Disk
 Volume Serial Number is 8E06-0977

 Directory of C:\pythontest\youtube_uploader_selenium

02/08/2022  11:31    <DIR>          .
02/08/2022  11:31    <DIR>          ..
01/08/2022  01:07             1,588 .gitignore
20/04/2020  22:22           125,179 blah.mp4
01/08/2022  01:07             1,093 LICENSE
01/08/2022  01:07             3,247 README.md
01/08/2022  01:07                25 requirements.txt
01/08/2022  01:07               865 upload.py
02/08/2022  11:31    <DIR>          youtube_uploader_selenium
               6 File(s)        131,997 bytes
               3 Dir(s)   9,813,024,768 bytes free

C:\pythontest\youtube_uploader_selenium>

C:\pythontest\youtube_uploader_selenium>python3 upload.py --video blah.mp4
Traceback (most recent call last):
  File "C:\pythontest\youtube_uploader_selenium\upload.py", line 22, in <module>
    main(args.video, args.meta, args.thumbnail)
  File "C:\pythontest\youtube_uploader_selenium\upload.py", line 7, in main
    uploader = YouTubeUploader(video_path, metadata_path, thumbnail_path)
  File "C:\pythontest\youtube_uploader_selenium\youtube_uploader_selenium\__init__.py", line 33, in __init__
    self.browser = Firefox(current_working_dir, current_working_dir)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium_firefox\firefox.py", line 86, in __init__
    self.driver = webdriver.Firefox(firefox_profile=profile, firefox_options=options)
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_options'

C:\pythontest\youtube_uploader_selenium>

The history before the above is 

A previous error I got was this one https://github.com/linouk23/youtube_uploader_selenium/issues/64   Then I installed selenium_firefox the module e.g. pip3 install selenium_firefox  or pip install selenium_firefox

Then I got this error https://github.com/linouk23/youtube_uploader_selenium/issues/50  and did pip install selenium_firefox==0.2.7

Then getting this TypeError: WebDriver  error.    https://github.com/linouk23/youtube_uploader_selenium/issues/57  did suggestion of pip install selenium==3.141.0

C:\pythontest\youtube_uploader_selenium>pip install selenium==3.141.0
Collecting selenium==3.141.0
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
     ---------------------------------------- 904.6/904.6 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: urllib3 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from selenium==3.141.0) (1.26.11)
Installing collected packages: selenium
  Attempting uninstall: selenium
    Found existing installation: selenium 4.3.0
    Uninstalling selenium-4.3.0:
      Successfully uninstalled selenium-4.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
selenium-browser 0.0.15 requires selenium>=4.0.0b4, but you have selenium 3.141.0 which is incompatible.
Successfully installed selenium-3.141.0

C:\pythontest\youtube_uploader_selenium>python3 upload.py --video blah.mp4
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\pythontest\youtube_uploader_selenium\upload.py", line 22, in <module>
    main(args.video, args.meta, args.thumbnail)
  File "C:\pythontest\youtube_uploader_selenium\upload.py", line 7, in main
    uploader = YouTubeUploader(video_path, metadata_path, thumbnail_path)
  File "C:\pythontest\youtube_uploader_selenium\youtube_uploader_selenium\__init__.py", line 33, in __init__
    self.browser = Firefox(current_working_dir, current_working_dir)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium_firefox\firefox.py", line 86, in __init__
    self.driver = webdriver.Firefox(firefox_profile=profile, firefox_options=options)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

C:\pythontest\youtube_uploader_selenium>path
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\ZeroTier\One\;C:\Program Files\Git\cmd;C:\Users\USER\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Nmap;C:\Program Files\Windows NT\Accessories;C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts;

C:\pythontest\youtube_uploader_selenium>"C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\geckodriver-path.exe"

C:\pythontest\youtube_uploader_selenium>where geckodriver-path.exe
C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\geckodriver-path.exe

C:\pythontest\youtube_uploader_selenium>
C:\pythontest\youtube_uploader_selenium>

(that directory with geckodriver-path is in my user path.. (it's not in my system path 'cos adding into system path seems to be greyed out in win10 home i'm using, for whatever reason), but geckodriver.exe is accessible from cmd in that it's even in the PATH and 'where' picks it up.  So the message about an error regarding that the executable needing to be in the path is not a message it should be giving me, because it is there. And that's besides the WebDriverException error.

**Comment by gartha1** [comment]
Okay I got a bit further now. Within the FAQ of the Readme.me  , it appears that actually part of installing this thing is you have to download "gecko driver",  geckodriver.exe in the case of windows,  from  https://github.com/mozilla/geckodriver/releases

And that's the file that needs to be in the path.
