### ISSUE TITLE
video is being set to draft though i want it set to private

### ISSUE THREAD

**Issue by gartha1** [linouk23/youtube_uploader_selenium#71]
video is being set to draft though i want it set to private

i'm fine with the video title for blah.mp4 being blah.. So I don't mind re not having a metadata file.

But I want it to be private not draft.

Not sure if this output is relevant..

C:\pythontest\linouk_youtube_uploader_selenium>python3 upload.py --video blah.mp4
WARNING:youtube_uploader_selenium:The video title was not found in a metadata file
WARNING:youtube_uploader_selenium:The video title was set to blah
WARNING:youtube_uploader_selenium:The video description was not found in a metadata file
DEBUG:youtube_uploader_selenium:Attached video blah.mp4
DEBUG:youtube_uploader_selenium:The video title was set to "blah"
DEBUG:youtube_uploader_selenium:Selected "VIDEO_MADE_FOR_KIDS_NOT_MFK"
'NoneType' object has no attribute 'click'
Traceback (most recent call last):
  File "C:\pythontest\linouk_youtube_uploader_selenium\upload.py", line 23, in <module>
    main(args.video, args.meta, args.thumbnail)
  File "C:\pythontest\linouk_youtube_uploader_selenium\upload.py", line 9, in main
    was_video_uploaded, video_id = uploader.upload()
  File "C:\pythontest\linouk_youtube_uploader_selenium\youtube_uploader_selenium\__init__.py", line 57, in upload
    return self.__upload()
  File "C:\pythontest\linouk_youtube_uploader_selenium\youtube_uploader_selenium\__init__.py", line 129, in __upload
    self.browser.find(By.XPATH, Constant.MORE_BUTTON).click()
AttributeError: 'NoneType' object has no attribute 'click'

C:\pythontest\linouk_youtube_uploader_selenium>

Thanks

**Comment by gartha1** [comment]
It might be that it clicked something before it appeared.. I loaded the code into VS Code, commented out parts I didn't need.. like the "advanced options" where it was doing some tags/metadata.. I put a sleep line in..

Then I looked at what it was clicking , it was clicking a "next" button. I just got it to click the buttons I wanted.

I also simplified it a bit 'cos it's going to the setting to set it as "not for kids".. maybe a good option maybe youtube bothers the user  or uploader less when it's that setting. But what I did was set the whole channel to "not for kids", so I don't have to do that setting for each video so then there are less things that need clicking.  I commented out the clicking 'next', and I found the buttons I wanted clicking, like the visibility option , and then "private" option, with the aid of the web browser's inspector.  

It only does one video at a time, as it stands, (opens the browser, uploads a video, closes the browser), but seems that's all it's meant to do.. and would need adjusting to do more I guess.
